version: "3.9"
services:
    webapi:
        container_name: webapi
        image: docker.io/library/productstore
        build:
            context: ./src
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        depends_on:
          - database
        environment:
            CONNECTION_STRING: "Server=sqlserver;Database=ProductStore;User Id=SA;Password=Passwordcomplex6690;MultipleActiveResultSets=true;TrustServerCertificate=True"
    database:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server
        environment:
            - ACCEPT_EULA=y
            - SA_PASSWORD=Passwordcomplex6690
        ports:
            - "1433:1433"
        depends_on:
          - redis
        volumes:
            - sql_server_data:/var/opt/mssql
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"

volumes:
    sql_server_data: {}
